// Core package public API
// Types (enums and interfaces)
export {
  UserRole,
  InterviewLevel,
  InterviewPhase,
  SpeakerRole,
  Recommendation,
  AuditAction,
  type BaseEntity,
  type AuditableEntity,
  type JwtPayload,
  type User,
  type CandidateProfile,
  type RecruiterProfile,
  type Scenario,
  type Rubric,
  type RubricCriterion,
  type InterviewSession,
  type PhaseTransition,
  type Turn,
  type ScoreCard,
  type ScoreCardCriterion,
  type Report,
  type ModelConfig,
  type AuditLog,
  // Legacy alias
  type SpeakingParty,
} from './types.js';

// Zod schemas
export {
  BaseSchema,
  AuditableSchema,
  RegisterSchema,
  LoginSchema,
  ChangePasswordSchema,
  ProfileUpdateSchema,
  CandidateProfileCreateSchema,
  CandidateProfileUpdateSchema,
  RecruiterProfileCreateSchema,
  RecruiterProfileUpdateSchema,
  ScenarioCreateSchema,
  ScenarioUpdateSchema,
  RubricCriterionSchema,
  RubricCreateSchema,
  RubricUpdateSchema,
  PhaseTransitionSchema,
  InterviewSessionCreateSchema,
  InterviewSessionUpdateSchema,
  InterviewSessionSchema,
  TurnCreateSchema,
  TurnSchema,
  ScoreCardCriterionSchema,
  ScoreCardCreateSchema,
  ScoreCardSchema,
  ScoreCardCriterionFullSchema,
  ReportCreateSchema,
  ReportSchema,
  ModelConfigCreateSchema,
  ModelConfigUpdateSchema,
  ModelConfigSchema,
  PartialTranscriptSchema,
  FinalTranscriptSchema,
  AiTextSchema,
  StateSchema,
  ErrorSchema,
  SessionCompleteSchema,
  AgentDataMessageSchema,
  ClientEventSchema,
  CandidateMetadataUpdateSchema,
  ClientDataMessageSchema,
  AuditLogSchema,
  AuditLogCreateSchema,
  CriterionScoreSchema,
  EvaluationResultSchema,
} from './schemas.js';

// Inferred types (from schemas)
export type {
  RegisterInput,
  LoginInput,
  ChangePasswordInput,
  ProfileUpdateInput,
  CandidateProfileCreateInput,
  CandidateProfileUpdateInput,
  RecruiterProfileCreateInput,
  RecruiterProfileUpdateInput,
  ScenarioCreateInput,
  ScenarioUpdateInput,
  RubricCreateInput,
  RubricUpdateInput,
  InterviewSessionCreateInput,
  InterviewSessionUpdateInput,
  TurnCreateInput,
  ScoreCardCreateInput,
  ReportCreateInput,
  ModelConfigCreateInput,
  ModelConfigUpdateInput,
  AgentDataMessage,
  ClientDataMessage,
  AuditLogCreateInput,
  EvaluationResultInput,
} from './schemas.js';

// Adapters, prompts, data-channel utilities
export * from './adapters.js';
export * from './prompts.js';
export * from './data-channel.js';

// State machine
export {
  PHASE_TRANSITIONS,
  TERMINAL_PHASES,
  ACTIVE_PHASES,
  canTransition,
  isTerminalPhase,
  isActivePhase,
  getAllowedTransitions,
  validateTransition,
  InvalidPhaseTransitionError,
  createPhaseTransition,
  InterviewStateMachine,
  type PhaseTransitionEntry,
} from './state-machine.js';
